# Generated by Django 6.0.4 on 2026-04-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_pedido_detallepedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado')], default='Pendiente', max_length=20),
        ),
    ]
