# Generated by Django 6.0.4 on 2026-05-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_detallepedido_variante_producto_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='varianteproducto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
