# Generated by Django 6.0.4 on 2026-05-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_varianteproducto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
